### ISSUE TITLE
Extension can't be loaded due to an error

### ISSUE THREAD

**Issue by isantop** [kylecorry31/gnome-shell-extension-pop-battery-icon-fix#4]
I just caught this today. When I open Tweak tool, I get a problem with it and see this error in the log:

```
Extension "batteryiconfix@kylecorry31.github.io" had error: TypeError: this.power.prototype is undefined
```

Am I missing a dependency, or is this an error (or is the extension out of date?)

**Comment by kylecorry31** [comment]
I believe I fixed that in the latest version. I'll double check that the code is actually on GitHub

**Comment by isantop** [comment]
Indeed, seems to be fixed.
